"""Adicionando campo notificado ao agendamento

Revision ID: 1ccdd419b8c5
Revises: 
Create Date: 2024-11-07 19:01:58.950753

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ccdd419b8c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notificado', sa.Boolean(), nullable=True))

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('email')

    with op.batch_alter_table('servico', schema=None) as batch_op:
        batch_op.alter_column('preco',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servico', schema=None) as batch_op:
        batch_op.alter_column('preco',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=100), nullable=False))

    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.drop_column('notificado')

    # ### end Alembic commands ###
